name: Playwright Tests
on:
  deployment_status: # Startet erst, wenn das Deployment fertig ist (optional)
  push:
    branches: [ main ] # Oder einfach bei jedem Push auf Main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-jammy # Das Docker Image!
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: npm install
      
    - name: Run Playwright tests
      run: npx playwright test
      
    - name: Upload Report
      if: always() # Auch hochladen, wenn Tests fehlschlagen
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
